[package]
name = "tree-sitter-coconut"
description = "Coconut grammar for tree-sitter"
version = "0.23.2"
authors = [
]
license = "MIT"
keywords = ["incremental", "parsing", "tree-sitter", "python", "coconut"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/aidanmontare-fed/tree-sitter-coconut"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1.0"

[build-dependencies]
cc = "1.1.15"

[dev-dependencies]
tree-sitter = "0.23"
